// Rules that shipped on some pages but not others, kept page-scoped.
// Rendered into a <style> by the page's shell so nothing can leak across
// routes. Generated by .migration/build-css.mjs — edit that, not this.

export const PAGE_CSS = {
  home: `
@keyframes float{50%{transform:translateY(-10px) rotate(3deg)}}
[data-boldness]{font-size:min(6rem,22cqw) !important}
/* hero background slideshow */
@keyframes heroFill1{from{transform:scaleX(0)}to{transform:scaleX(1)}}
@keyframes heroFill2{from{transform:scaleX(0)}to{transform:scaleX(1)}}
@keyframes heroFill3{from{transform:scaleX(0)}to{transform:scaleX(1)}}
@keyframes heroGrain{0%,100%{opacity:0.05}50%{opacity:0.09}}
@media (max-width:1080px){
  [data-hero-badge]{display:none !important}
}
@media (max-width:720px){
  [data-hero-copy]{gap:1.6rem !important}
}
`,
  work: `
/* --- ambient hero motion --- */
@keyframes orbDrift{0%,100%{transform:translate3d(0,0,0) scale(1)}50%{transform:translate3d(-2.4%,-1.8%,0) scale(1.05)}}
@keyframes numFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}
[data-orb]{animation:orbDrift 19s ease-in-out infinite;will-change:transform}
[data-numeral]{animation:numFloat 9s ease-in-out infinite;will-change:transform}
[data-lift]{transition:transform .3s cubic-bezier(.2,.8,.2,1),background .3s ease,border-color .3s ease,color .3s ease}
[data-lift]:hover{transform:translateY(-2px)}
@keyframes pop{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:none}}
@keyframes popAlt{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:none}}
`,
  services: `
/* --- ambient hero motion --- */
@keyframes orbDrift{0%,100%{transform:translate3d(0,0,0) scale(1)}50%{transform:translate3d(-2.4%,-1.8%,0) scale(1.05)}}
@keyframes numFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}
[data-orb]{animation:orbDrift 19s ease-in-out infinite;will-change:transform}
[data-numeral]{animation:numFloat 9s ease-in-out infinite;will-change:transform}
`,
  about: `
/* --- ambient hero motion --- */
@keyframes orbDrift{0%,100%{transform:translate3d(0,0,0) scale(1)}50%{transform:translate3d(-2.4%,-1.8%,0) scale(1.05)}}
@keyframes numFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}
[data-orb]{animation:orbDrift 19s ease-in-out infinite;will-change:transform}
[data-numeral]{animation:numFloat 9s ease-in-out infinite;will-change:transform}
`,
  contact: `
*{box-sizing:border-box}
input,select,textarea,button{font:inherit;max-width:100%}
@media (max-width:900px){form{grid-template-columns:1fr !important}}
input:focus,select:focus,textarea:focus{border-color:#ef2329;outline:none;box-shadow:0 0 0 3px rgba(239,35,41,0.12)}
`,
};
