// Generated by .migration/build-pseudo.mjs — do not edit.
//
// Usage mirrors the markup being ported, so a style-hover attribute becomes:
//
//   <a style={{...}} className={sx({ hover: 'color:#f2eee5;box-shadow:inset 0 -2px 0 #ef2329' })}>
//
// An unknown declaration string throws rather than silently dropping the state,
// so a typo during the port cannot quietly change a hover.

const CLASSES = {
  "hover|color:#f2eee5;box-shadow:inset 0 -2px 0 #ef2329": 'scp0',
  "hover|background:#fff;border-color:#fff;color:#ef2329;transform:translateY(-2px);box-shadow:0 12px 30px rgba(239,35,41,0.35)": 'scp1',
  "active|transform:translateY(0) scale(0.98)": 'scp2',
  "hover|background:#fff;border-color:#fff;color:#ef2329;transform:translateY(-2px)": 'scp3',
  "hover|animation-play-state:paused": 'scp4',
  "hover|background:#ef2329;color:#fff;--ic:#fff;transform:translateY(-4px) scale(1.01);box-shadow:0 20px 48px rgba(0,0,0,0.45)": 'scp5',
  "hover|border-color:rgba(239,35,41,0.8);transform:translateY(-8px) scale(1.012);box-shadow:0 24px 60px rgba(0,0,0,0.55);--is:1.08": 'scp6',
  "hover|background:#f2eee5;color:#050505;transform:translateY(-2px);box-shadow:0 12px 30px rgba(0,0,0,0.45)": 'scp7',
  "hover|transform:translateY(-6px) scale(1.008);border-color:rgba(239,35,41,0.6);box-shadow:0 26px 64px rgba(0,0,0,0.6)": 'scp8',
  "hover|background:#fff;color:#ef2329;transform:translateY(-2px);white-space:nowrap": 'scp9',
  "hover|color:#f2eee5;transform:translateX(3px)": 'scpa',
  "hover|transform:translateY(-6px);border-color:rgba(239,35,41,0.6);box-shadow:0 26px 64px rgba(0,0,0,0.6)": 'scpb',
  "hover|border-color:rgba(239,35,41,0.55);box-shadow:0 26px 64px rgba(0,0,0,0.5)": 'scpc',
  "focus|transform:translateY(-1px);border-color:#ef2329;box-shadow:0 0 0 3px rgba(239,35,41,0.16)": 'scpd',
  "hover|background:#fff;border-color:#fff;color:#ef2329;transform:translateY(-2px);cursor:pointer": 'scpe',
};

export function sx(states) {
  const out = [];
  for (const pseudo of Object.keys(states)) {
    const css = states[pseudo];
    if (!css) continue;
    const cls = CLASSES[pseudo + '|' + css];
    if (!cls) {
      throw new Error(
        `no generated class for style-${pseudo}="${css}" — it is not in any extracted template. ` +
          'Copy the declaration exactly, or re-run .migration/build-pseudo.mjs.',
      );
    }
    out.push(cls);
  }
  return out.join(' ');
}
