// Reproduces dc-runtime's pseudo-class mechanism as static CSS.
//
// The runtime read `style-hover="color:#fff;transform:translateY(-2px)"` off an
// element and, at render time, minted a class:
//
//   .scp3:hover{color:#fff !important;transform:translateY(-2px) !important}
//
// deduping by (pseudo, css). ::before/::after were the exception — those were
// NOT made !important. This script does the same thing ahead of time, over the
// style-* attributes found in the extracted templates, so the port needs no
// runtime stylesheet injection and no invented values.
//
//   node .migration/build-pseudo.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(HERE, 'src', 'pages');
const APP = path.join(HERE, '..', 'next', 'app');
const PAGES = ['home', 'work', 'services', 'about', 'contact'];

// Ported from dc-runtime's importantify(): split on top-level semicolons only,
// so a `;` inside url() or a quoted string does not end a declaration.
function importantify(css) {
  const decls = [];
  let start = 0;
  let depth = 0;
  let quote = null;
  for (let i = 0; i < css.length; i++) {
    const c = css[i];
    if (quote) {
      if (c === quote && css[i - 1] !== '\\') quote = null;
      continue;
    }
    if (c === '"' || c === "'") quote = c;
    else if (c === '(') depth++;
    else if (c === ')') depth--;
    else if (c === ';' && depth === 0) {
      decls.push(css.slice(start, i));
      start = i + 1;
    }
  }
  decls.push(css.slice(start));
  return decls
    .map((d) => d.trim())
    .filter(Boolean)
    .map((d) => (/!\s*important$/i.test(d) ? d : d + ' !important'))
    .join(';');
}

// Collect every style-<pseudo>="…" in template order, per page.
const found = [];
const perPage = {};
for (const page of PAGES) {
  const html = fs.readFileSync(path.join(SRC, page, 'template.resolved.html'), 'utf8');
  const hits = [...html.matchAll(/\sstyle-([a-z-]+)="([^"]*)"/g)].map((m) => ({ pseudo: m[1], css: m[2] }));
  perPage[page] = hits.length;
  found.push(...hits);
}

// Dedupe by (pseudo, css) exactly as the runtime's cache key did.
const classes = new Map();
for (const { pseudo, css } of found) {
  const k = pseudo + '|' + css;
  if (!classes.has(k)) classes.set(k, { pseudo, css, cls: 'scp' + classes.size.toString(36) });
}

const rules = [...classes.values()].map(({ pseudo, css, cls }) => {
  const isElement = pseudo === 'before' || pseudo === 'after';
  const sel = isElement ? `.${cls}::${pseudo}` : `.${cls}:${pseudo}`;
  return `${sel}{${isElement ? css : importantify(css)}}`;
});

fs.writeFileSync(path.join(APP, 'pseudo.css'), `/* Generated by .migration/build-pseudo.mjs — do not edit.
 *
 * dc-runtime minted these classes at render time from style-<pseudo> attributes,
 * making every declaration !important (which is how a stylesheet rule beats the
 * element's own inline style). Same values, same dedupe, emitted ahead of time.
 */

${rules.join('\n')}
`);

const map = [...classes.values()]
  .map(({ pseudo, css, cls }) => `  ${JSON.stringify(pseudo + '|' + css)}: '${cls}',`)
  .join('\n');

fs.writeFileSync(path.join(APP, 'pseudo.js'), `// Generated by .migration/build-pseudo.mjs — do not edit.
//
// Usage mirrors the markup being ported, so a style-hover attribute becomes:
//
//   <a style={{...}} className={sx({ hover: 'color:#f2eee5;box-shadow:inset 0 -2px 0 #ef2329' })}>
//
// An unknown declaration string throws rather than silently dropping the state,
// so a typo during the port cannot quietly change a hover.

const CLASSES = {
${map}
};

export function sx(states) {
  const out = [];
  for (const pseudo of Object.keys(states)) {
    const css = states[pseudo];
    if (!css) continue;
    const cls = CLASSES[pseudo + '|' + css];
    if (!cls) {
      throw new Error(
        \`no generated class for style-\${pseudo}="\${css}" — it is not in any extracted template. \` +
          'Copy the declaration exactly, or re-run .migration/build-pseudo.mjs.',
      );
    }
    out.push(cls);
  }
  return out.join(' ');
}
`);

console.log(`style-* attributes found: ${found.length}`);
for (const p of PAGES) console.log(`  ${p.padEnd(9)} ${perPage[p]}`);
console.log(`distinct (pseudo, css) pairs: ${classes.size}`);
const byPseudo = {};
for (const { pseudo } of found) byPseudo[pseudo] = (byPseudo[pseudo] || 0) + 1;
console.log('by pseudo:', JSON.stringify(byPseudo));
