// Splits the five per-page stylesheets into one shared globals.css plus a
// per-page tail, and proves the split is lossless: shared + tail must contain
// exactly the rules the original page shipped, no more and no fewer.
//
//   node .migration/build-css.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(HERE, 'src');
const APP = path.join(HERE, '..', 'next', 'app');
const PAGES = ['home', 'work', 'services', 'about', 'contact'];

// The dc-runtime injected this on every page; without it the ported markup
// sits in a differently-sized root box.
const FULL_PAGE_CSS = 'html,body{height:100%;margin:0}\n#dc-root{height:100%}';

// Split a stylesheet into top-level tokens: comments and complete rules
// (including @media blocks with their nested contents).
function tokenize(css) {
  const out = [];
  let buf = '';
  let depth = 0;
  for (let i = 0; i < css.length; i++) {
    if (depth === 0 && css[i] === '/' && css[i + 1] === '*') {
      const end = css.indexOf('*/', i + 2);
      if (buf.trim()) { out.push(buf.trim()); buf = ''; }
      out.push(css.slice(i, end + 2).trim());
      i = end + 1;
      continue;
    }
    buf += css[i];
    if (css[i] === '{') depth++;
    else if (css[i] === '}') {
      depth--;
      if (depth === 0) { out.push(buf.trim()); buf = ''; }
    }
  }
  if (buf.trim()) out.push(buf.trim());
  return out;
}

// Whitespace-insensitive identity, so indentation differences between pages
// never masquerade as a rule difference.
const key = (rule) => rule.replace(/\s+/g, ' ').trim();

const sheets = Object.fromEntries(
  PAGES.map((p) => [p, tokenize(fs.readFileSync(path.join(SRC, 'pages', p, 'global.css'), 'utf8'))]),
);

// Shared = present in every page, ordered as Contact (the page with no extra
// rules interleaved) lays them out.
const inAll = (k) => PAGES.every((p) => sheets[p].some((r) => key(r) === k));
const shared = sheets.contact.filter((r) => inAll(key(r)));
const sharedKeys = new Set(shared.map(key));

const tails = {};
for (const p of PAGES) tails[p] = sheets[p].filter((r) => !sharedKeys.has(key(r)));

// ── verification ─────────────────────────────────────────────────────────────
let bad = 0;
for (const p of PAGES) {
  const rebuilt = [...shared, ...tails[p]].map(key).sort();
  const original = sheets[p].map(key).sort();
  const ok = rebuilt.length === original.length && rebuilt.every((r, i) => r === original[i]);
  if (!ok) {
    bad++;
    console.log(`  MISMATCH ${p}`);
    const missing = original.filter((r) => !rebuilt.includes(r));
    const extra = rebuilt.filter((r) => !original.includes(r));
    for (const m of missing) console.log(`    missing: ${m.slice(0, 90)}`);
    for (const e of extra) console.log(`    extra:   ${e.slice(0, 90)}`);
  }
}
if (bad) process.exit(1);

// ── emit ─────────────────────────────────────────────────────────────────────
const fonts = fs.readFileSync(path.join(SRC, 'fonts.resolved.css'), 'utf8').trim();
const dedent = (rules) => rules.map((r) => r.replace(/^ {2}/gm, '')).join('\n');

fs.writeFileSync(path.join(APP, 'globals.css'), `/* Ported verbatim from the bundled site. Do not restyle.
 *
 * 1. @font-face — the exact rules the bundle shipped, pointing at the woff2
 *    files extracted from it (same weights, unicode-ranges and font-display).
 * 2. The dc-runtime's full-page rules.
 * 3. The stylesheet every page shared. Page-specific rules live in page-css.js
 *    because they are NOT interchangeable — Contact's \`*{box-sizing:border-box}\`
 *    alone moves 30-59% of the pixels on the other four pages.
 */

${fonts}

${FULL_PAGE_CSS}

${dedent(shared)}
`);

const entries = PAGES.map((p) => `  ${p}: \`\n${tails[p].map((r) => r.replace(/^ {2}/gm, '')).join('\n')}\n\`,`).join('\n');
fs.writeFileSync(path.join(APP, 'page-css.js'), `// Rules that shipped on some pages but not others, kept page-scoped.
// Rendered into a <style> by the page's shell so nothing can leak across
// routes. Generated by .migration/build-css.mjs — edit that, not this.

export const PAGE_CSS = {
${entries}
};
`);

console.log(`shared rules: ${shared.length}`);
for (const p of PAGES) console.log(`  ${p.padEnd(9)} +${tails[p].length} page-specific`);
console.log('\nsplit verified lossless against all five original stylesheets');
